# Generated by Django 3.2.9 on 2021-12-26 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emmloyeeid', models.CharField(default='', max_length=14, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('designation', models.CharField(choices=[('DISTRICT DEVELOPMENT MANAGER', 'DISTRICT DEVELOPMENT MANAGER'), ('BLOCK DEVELOPMENT MANAGER', 'BLOCK DEVELOPMENT MANAGER'), ('FIELD EXECUTIVE', 'FIELD EXECUTIVE'), ('AGRICULTURAL ADVISOR', 'AGRICULTURAL ADVISOR'), ('COMPUTER TRAINER', 'COMPUTER TRAINER'), ('BEAUTICIAN', 'BEAUTICIAN'), ('TAILORING', 'TAILORING'), ('Office Boy/Peon', 'Office Boy/Peon'), ('Banking Trainer', 'Banking Trainer'), ('Regional Manager', 'Regional Manager'), ('Accountant/Cashier', 'Accountant/Cashier'), ('Receptionist', 'Receptionist')], max_length=32)),
                ('job_location', models.CharField(default='', max_length=100)),
                ('bloodgroup', models.CharField(default='', max_length=10)),
                ('dob', models.DateField()),
                ('Address', models.CharField(default='', max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Employee')),
                ('health_card_created', models.IntegerField()),
                ('kisan_card_created', models.IntegerField()),
                ('membership_card_created', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Employee Profiles',
                'db_table': 'profile',
            },
        ),
    ]
