# Generated by Django 3.2.9 on 2021-12-26 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeProfile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='health_card_created',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='kisan_card_created',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='membership_card_created',
        ),
    ]
