# Generated by Django 3.2.7 on 2021-12-16 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeprofile',
            options={'verbose_name_plural': 'Employee Profiles'},
        ),
    ]
