# Generated by Django 3.2.9 on 2021-12-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeProfile', '0002_auto_20211227_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='health_card_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='kisan_card_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='membership_card_created',
            field=models.IntegerField(default=0),
        ),
    ]
