# Generated by Django 3.2.10 on 2021-12-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeProfile', '0003_auto_20211227_0141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='health_card_created',
            new_name='current_month_health_card_created',
        ),
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='kisan_card_created',
            new_name='current_month_kisan_card_created',
        ),
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='membership_card_created',
            new_name='current_month_membership_card_created',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='previous_month_health_card_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='previous_month_kisan_card_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='previous_month_membership_card_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='total_health_card_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='total_kisan_card_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='total_membership_card_created',
            field=models.IntegerField(default=0),
        ),
    ]
