# Generated by Django 3.2.7 on 2022-02-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeProfile', '0005_alter_employeeprofile_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='can_accept_cash',
            field=models.BooleanField(default=False),
        ),
    ]
