# Generated by Django 3.2.4 on 2022-02-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeProfile', '0006_employeeprofile_can_accept_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='designation',
            field=models.CharField(choices=[('DISTRICT DEVELOPMENT MANAGER', 'DISTRICT DEVELOPMENT MANAGER'), ('BLOCK DEVELOPMENT MANAGER', 'BLOCK DEVELOPMENT MANAGER'), ('FIELD EXECUTIVE', 'FIELD EXECUTIVE'), ('AGRICULTURAL ADVISOR', 'AGRICULTURAL ADVISOR'), ('COMPUTER TRAINER', 'COMPUTER TRAINER'), ('BEAUTICIAN', 'BEAUTICIAN'), ('TAILORING', 'TAILORING'), ('Office Boy/Peon', 'Office Boy/Peon'), ('Banking Trainer', 'Banking Trainer'), ('Regional Manager', 'Regional Manager'), ('Accountant/Cashier', 'Accountant/Cashier'), ('Receptionist', 'Receptionist'), ('Vendor', 'Vendor')], max_length=32),
        ),
    ]
