# Generated by Django 3.2.4 on 2022-03-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeProfile', '0007_alter_employeeprofile_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='cash_mode_current_month_health_card_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='cash_mode_current_month_kisan_card_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='cash_mode_current_month_membership_card_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='cash_mode_previous_month_health_card_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='cash_mode_previous_month_kisan_card_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='cash_mode_previous_month_membership_card_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='cash_mode_total_health_card_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='cash_mode_total_kisan_card_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='cash_mode_total_membership_card_created',
            field=models.IntegerField(default=0),
        ),
    ]
