# Generated by Django 3.2.11 on 2022-01-12 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ifheplapp', '0008_delete_jobapply'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('dob', models.CharField(default='', max_length=100)),
                ('mobile_number', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('alt_mobile_no', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('disability', models.CharField(blank=True, default='', max_length=100)),
                ('father_Husband_name', models.CharField(blank=True, default='', max_length=100)),
                ('mother_name', models.CharField(blank=True, default='', max_length=100)),
                ('aadhar_no', models.CharField(blank=True, default='', max_length=12)),
                ('pan_no', models.CharField(blank=True, default='', max_length=100)),
                ('village', models.CharField(blank=True, default='', max_length=100)),
                ('po', models.CharField(blank=True, default='', max_length=100)),
                ('ps', models.CharField(blank=True, default='', max_length=100)),
                ('block', models.CharField(blank=True, default='', max_length=100)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('pin_code', models.CharField(blank=True, default='', max_length=100)),
                ('board_10', models.CharField(blank=True, default='', max_length=100)),
                ('school_10', models.CharField(blank=True, default='', max_length=100)),
                ('passing_10', models.CharField(blank=True, default='', max_length=100)),
                ('roll_10', models.CharField(blank=True, default='', max_length=100)),
                ('mark_10', models.CharField(blank=True, default='', max_length=100)),
                ('percentage_10', models.CharField(blank=True, default='', max_length=100)),
                ('board_12', models.CharField(blank=True, default='', max_length=100)),
                ('school_12', models.CharField(blank=True, default='', max_length=100)),
                ('passing_12', models.CharField(blank=True, default='', max_length=100)),
                ('roll_12', models.CharField(blank=True, default='', max_length=100)),
                ('mark_12', models.CharField(blank=True, default='', max_length=100)),
                ('percentage_12', models.CharField(blank=True, default='', max_length=100)),
                ('univ_graduation', models.CharField(blank=True, default='', max_length=100)),
                ('insti_graduation', models.CharField(blank=True, default='', max_length=100)),
                ('passing_graduation', models.CharField(blank=True, default='', max_length=100)),
                ('roll_graduation', models.CharField(blank=True, default='', max_length=100)),
                ('mark_graduation', models.CharField(blank=True, default='', max_length=100)),
                ('percentage_graduation', models.CharField(blank=True, default='', max_length=100)),
                ('univ_master', models.CharField(blank=True, default='', max_length=100)),
                ('insti_master', models.CharField(blank=True, default='', max_length=100)),
                ('passing_master', models.CharField(blank=True, default='', max_length=100)),
                ('roll_master', models.CharField(blank=True, default='', max_length=100)),
                ('mark_master', models.CharField(blank=True, default='', max_length=100)),
                ('percentage_master', models.CharField(blank=True, default='', max_length=100)),
                ('edudoc', models.FileField(blank=True, upload_to='Job/Document/')),
                ('imgs', models.FileField(blank=True, upload_to='Job/Image/')),
                ('sign', models.FileField(blank=True, upload_to='Job/Signature/')),
                ('submitted_on', models.DateField()),
                ('approve', models.BooleanField(default=False)),
                ('reject', models.BooleanField(default=False)),
                ('reference_number', models.CharField(default='', max_length=15)),
                ('applied_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifheplapp.jobs')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
