# Generated by Django 3.2.11 on 2022-01-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApplications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_application',
            old_name='approve',
            new_name='accept',
        ),
        migrations.AddField(
            model_name='job_application',
            name='submitted',
            field=models.BooleanField(default=True),
        ),
    ]
