# Generated by Django 3.2.7 on 2022-02-11 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeProfile', '0005_alter_employeeprofile_job_location'),
        ('jobApplications', '0002_auto_20220112_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_application',
            old_name='board_10',
            new_name='bloodgroup',
        ),
        migrations.RenameField(
            model_name='job_application',
            old_name='board_12',
            new_name='extra_qualification_board_university',
        ),
        migrations.RenameField(
            model_name='job_application',
            old_name='insti_graduation',
            new_name='extra_qualification_marks_gpa',
        ),
        migrations.RenameField(
            model_name='job_application',
            old_name='insti_master',
            new_name='extra_qualification_passing_year',
        ),
        migrations.RenameField(
            model_name='job_application',
            old_name='mark_10',
            new_name='extra_qualification_percentage',
        ),
        migrations.RenameField(
            model_name='job_application',
            old_name='mark_12',
            new_name='extra_qualification_roll_number',
        ),
        migrations.RenameField(
            model_name='job_application',
            old_name='mark_graduation',
            new_name='extra_qualification_school_institute',
        ),
        migrations.RenameField(
            model_name='job_application',
            old_name='mark_master',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='job_application',
            old_name='passing_10',
            new_name='graduation_board_university',
        ),
        migrations.RenameField(
            model_name='job_application',
            old_name='passing_12',
            new_name='graduation_marks_gpa',
        ),
        migrations.RenameField(
            model_name='job_application',
            old_name='passing_graduation',
            new_name='graduation_passing_year',
        ),
        migrations.RenameField(
            model_name='job_application',
            old_name='passing_master',
            new_name='graduation_percentage',
        ),
        migrations.RenameField(
            model_name='job_application',
            old_name='percentage_10',
            new_name='graduation_roll_number',
        ),
        migrations.RenameField(
            model_name='job_application',
            old_name='percentage_12',
            new_name='graduation_school_institute',
        ),
        migrations.RenameField(
            model_name='job_application',
            old_name='percentage_graduation',
            new_name='higher_qualification_board_university',
        ),
        migrations.RenameField(
            model_name='job_application',
            old_name='percentage_master',
            new_name='higher_qualification_marks_gpa',
        ),
        migrations.RenameField(
            model_name='job_application',
            old_name='roll_10',
            new_name='higher_qualification_passing_year',
        ),
        migrations.RenameField(
            model_name='job_application',
            old_name='roll_12',
            new_name='higher_qualification_percentage',
        ),
        migrations.RenameField(
            model_name='job_application',
            old_name='roll_graduation',
            new_name='higher_qualification_roll_number',
        ),
        migrations.RenameField(
            model_name='job_application',
            old_name='roll_master',
            new_name='higher_qualification_school_institute',
        ),
        migrations.RenameField(
            model_name='job_application',
            old_name='school_10',
            new_name='intermediate_board_university',
        ),
        migrations.RenameField(
            model_name='job_application',
            old_name='school_12',
            new_name='intermediate_marks_gpa',
        ),
        migrations.RenameField(
            model_name='job_application',
            old_name='univ_graduation',
            new_name='intermediate_passing_year',
        ),
        migrations.RenameField(
            model_name='job_application',
            old_name='univ_master',
            new_name='intermediate_percentage',
        ),
        migrations.RenameField(
            model_name='job_application',
            old_name='imgs',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='job_application',
            name='edudoc',
        ),
        migrations.RemoveField(
            model_name='job_application',
            name='submitted',
        ),
        migrations.AddField(
            model_name='job_application',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job_application',
            name='employee_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_application', to='EmployeeProfile.employeeprofile'),
        ),
        migrations.AddField(
            model_name='job_application',
            name='intermediate_roll_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job_application',
            name='intermediate_school_institute',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job_application',
            name='matriculation_board_university',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job_application',
            name='matriculation_marks_gpa',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job_application',
            name='matriculation_passing_year',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job_application',
            name='matriculation_percentage',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job_application',
            name='matriculation_roll_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job_application',
            name='matriculation_school_institute',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job_application',
            name='order_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job_application',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job_application',
            name='payment_mode',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job_application',
            name='payment_status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job_application',
            name='razorpay_payment_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job_application',
            name='razorpay_signature',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job_application',
            name='transaction_date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='job_application',
            name='reference_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
