# Generated by Django 3.2.7 on 2021-11-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifheplapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcard',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='jobapply',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='kisancard',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='father_name',
        ),
        migrations.AddField(
            model_name='healthcard',
            name='father_Husband_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jobapply',
            name='father_Husband_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='kisancard',
            name='father_Husband_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='membership',
            name='father_Husband_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
