# Generated by Django 3.2.7 on 2021-11-05 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifheplapp', '0002_auto_20211104_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
