# Generated by Django 3.2.7 on 2021-12-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifheplapp', '0004_associatepartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcard',
            name='created',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kisancard',
            name='created',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='created',
            field=models.BooleanField(default=True),
        ),
    ]
