# Generated by Django 3.2.9 on 2021-12-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifheplapp', '0005_auto_20211226_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='created',
            field=models.BooleanField(default=False),
        ),
    ]
