# Generated by Django 3.2.11 on 2022-01-12 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifheplapp', '0007_auto_20211227_0135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApply',
        ),
    ]
