# Generated by Django 3.2.11 on 2022-01-13 04:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ifheplapp', '0008_delete_jobapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='associatepartner',
            name='partnerAddress',
            field=models.CharField(blank=True, default='', max_length=600),
        ),
        migrations.AddField(
            model_name='associatepartner',
            name='partnerImage',
            field=models.FileField(default=django.utils.timezone.now, upload_to='Associate Partner/'),
            preserve_default=False,
        ),
    ]
