# Generated by Django 3.2.7 on 2022-02-17 03:44

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifheplapp', '0011_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='sign',
        ),
        migrations.AddField(
            model_name='associatepartner',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=2, editable=False, populate_from='partnerName'),
            preserve_default=False,
        ),
    ]
