# Generated by Django 3.2.7 on 2022-02-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vendorApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('VendorID', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('dob', models.CharField(default='', max_length=100)),
                ('idtype', models.CharField(default='', max_length=100)),
                ('id_proof', models.CharField(blank=True, default='', max_length=100)),
                ('father_Husband_name', models.CharField(default='', max_length=100)),
                ('mother_name', models.CharField(default='', max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
                ('disability', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=100)),
                ('religion', models.CharField(default='', max_length=100)),
                ('marital_status', models.CharField(default='', max_length=100)),
                ('language_known', models.CharField(default='', max_length=100)),
                ('occupation', models.CharField(default='', max_length=100)),
                ('nominee_name', models.CharField(default='', max_length=100)),
                ('work_area', models.CharField(default='', max_length=100)),
                ('mobile_number', models.CharField(default='', max_length=100)),
                ('alt_mobile_no', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('village', models.CharField(default='', max_length=100)),
                ('po', models.CharField(default='', max_length=100)),
                ('ps', models.CharField(default='', max_length=100)),
                ('block', models.CharField(default='', max_length=100)),
                ('district', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('pin_code', models.CharField(default='', max_length=100)),
                ('accept_terms', models.BooleanField(default=False)),
                ('id_proof_document', models.FileField(upload_to='Vendor/ID_Proof/')),
                ('photo', models.FileField(upload_to='Vendor/Photo/')),
                ('signature', models.FileField(upload_to='Vendor/Signature/')),
                ('submitted_on', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('accept', models.BooleanField(default=False)),
                ('reject', models.BooleanField(default=False)),
                ('reference_number', models.CharField(default='', max_length=20)),
                ('order_id', models.CharField(default='', max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('razorpay_signature', models.CharField(default='', max_length=100)),
                ('razorpay_payment_id', models.CharField(default='', max_length=100)),
                ('transaction_date', models.CharField(default='', max_length=100)),
                ('payment_status', models.CharField(default='', max_length=100)),
                ('payment_mode', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
